language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: C6KL9WLAaYnHVSbJFF0bZJEgIgJgUL6rdztgyDds8UBKdHluQy+XiIaCilMJAeZb4sH4jVrPjVjsaShCwN22tAJy8zPRXx6rpGHtjUSkEuoRQkXQZ2BwadkNPJinp4/XNvA/D8us8Mz35GV76g8S9IamCS2MuxifpvfVuCxT4soRahyLOe1Vzxnu4LIvTBGXEAYAGPkc+p+2Kbo0hx1fSShqpyYM6+t8X24P3Ue5UjW1Tu8wxkBOg26C8zLD34lmxvPMB99c3IyB5YvoT/qzSfilEA1zPR8mzWyFebV9s1+s1Hhzwkd3G2X/fWcZtGSQ6z6kZpCu/v/U1WONaamj8WNt6UIJMLcQOod6HkKHxhMjTsPQ/fw1UOXc7X6PaH80KMMUUUCsRrjUd0IWYxb2lDtBdZ257Jdr+qlbPKkjq2jdEQedDQMj0aGlY8EbEBSZXCPPR9fEVmjGuXusdRW3l9720aHqIJtlorp96ic+uyP9r5fdC4bsEjTvW5bu0zfTtSYYJnQVZPQxTSKgcVAqQNgDVTYTZz/9aO2bhamVvuQsQpsibB6DRcsfTCWmcqXRjqt1qByTvBkqOdTDkCtgA5hecub7fdCJLTZ+Nxyy5rmdEoI5W1VmTQFvCPTdEFmgbs2CFuIQMZObFjPm3YXPvSYrNTjB+ZsvaypTTqeoBAw=
  app: curren